spring.application.name=distributors
spring.datasource.url=jdbc:mysql://localhost:3306/zawadi_distributors
spring.datasource.username=root
spring.datasource.password=NCT!mArK_9728x$

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true